### ISSUE TITLE
Regions tool map is not clickable as it once was

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/regions#100] opened 2023-04-11 04:37 UTC
Raised by a user in issue https://support.ehelp.edu.au/a/tickets/172633

Can the map on the 'Explore Regions' page be made clickable as it once was.  I am unable to select specific regions by clicking on the map.  Very difficult to find a region from the menus on the left if you don't know its exact title.

To reproduce:
* Go to regions.ala.org.au
* Click on 'Marine Parks'
* Click on an area
* Nothing happens

You have to navigate to the menu item to be able to click through to data. 

Reported by @peggynewman (cc: @sughics )

**Comment by sughics** [comment] 2023-05-08 07:37
issue caused by CORS error on a WMS request which is triggered on a map click. CORS headers on spatial-service need to be configured correctly for regions consumption
![Screenshot 2023-05-08 at 5 37 21 pm](https://user-images.githubusercontent.com/105408469/236764311-cdb0be0a-d41e-4156-a714-ad7291acd2a5.png)

**Comment by adam-collins** [comment] 2023-05-31 23:54
Fixed on production.

**Closed** 2023-06-13 00:44 UTC
